feat: e2e complete overhaul

diff --git a/spacesavers2_e2e b/spacesavers2_e2e
--- a/spacesavers2_e2e
+++ b/spacesavers2_e2e
@@ -11,10 +11,12 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 ARGPARSE_DESCRIPTION="End-to-end run of spacesavers2"
 source ${SCRIPT_DIR}/resources/argparse.bash || exit 1
 argparse "$@" <<EOF || exit 1
-parser.add_argument('-i','--infolder',required=True, help='Folder to run spacesavers_catalog on.')
+parser.add_argument('-f','--folder',required=True, help='Folder to run spacesavers_catalog on.')
 parser.add_argument('-p','--threads',required=False, help='number of threads to use', default=4)
+parser.add_argument('-l','--limit',required=False, help='limit for running spacesavers_grubbers', default=5)
+parser.add_argument('-v','--level',required=False, help='level for running spacesavers_blamematrix', default=3)
 parser.add_argument('-q','--quota',required=False, help='total size of the volume (default = 200 for /data/CCBR)', default=200)
-parser.add_argument('-o','--outfolder',required=True, help='Folder where all spacesavers_mimeo output files will be saved')
+parser.add_argument('-o','--outfolder',required=True, help='Folder where all spacesavers_e2e output files will be saved')
 EOF
 
 # assuming that python 3.11 is available with xxhash module
@@ -28,31 +30,67 @@ fi
 
 # run spacesavers2
 dt=$(date +%Y%m%d)
-prefix=$(echo "${dt}.${INFOLDER}"|sed "s/\//_/g")
-outfile_catalog="${prefix}.catalog"
-outfile_catalog_err="${prefix}.catalog_err"
-outfile_mimeo_log="${prefix}.mimeo_log"
-outfile_mimeo_err="${prefix}.mimeo_err"
+prefix=$(echo "${dt}.${FOLDER}"|sed "s/\//_/g")
+outfile_catalog="${OUTFOLDER}/${prefix}.catalog"
+outfile_catalog_err="${OUTFOLDER}/${prefix}.catalog.err"
+outfile_catalog_log="${OUTFOLDER}/${prefix}.catalog.log"
+outfile_mimeo_log="${OUTFOLDER}/${prefix}.mimeo.log"
+outfile_mimeo_err="${OUTFOLDER}/${prefix}.mimeo.err"
+
+outfile_blamematrix="${OUTFOLDER}/${prefix}.blamematrix.tsv"
+outfile_blamematrix_log="${OUTFOLDER}/${prefix}.blamematrix.log"
+outfile_blamematrix_err="${OUTFOLDER}/${prefix}.blamematrix.err"
 
 if [ ! -d $OUTFOLDER ];then mkdir -p $OUTFOLDER;fi
+
+# spacesavers2_catalog
 if [ "$?" == "0" ];then
 echo "Running spacesavers2_catalog" && \
-spacesavers2_catalog -f $INFOLDER -p $THREADS -e > ${OUTFOLDER}/${outfile_catalog} 2> ${OUTFOLDER}/${outfile_catalog_err}
+spacesavers2_catalog \
+    --folder $FOLDER \
+    --threads $THREADS \
+    --outfile ${outfile_catalog} \
+    --bottomhash \
+    > ${outfile_catalog_log} 2> ${outfile_catalog_err}
 fi
+
+# spacesavers2_mimeo
 if [ "$?" == "0" ];then
-echo "Running spacesavers2_mimeo" && \
-spacesavers2_mimeo -f ${OUTFOLDER}/${outfile_catalog} -o ${OUTFOLDER} -q $QUOTA -z -d 3 -p $prefix > ${OUTFOLDER}/${outfile_mimeo_log} 2> ${OUTFOLDER}/${outfile_mimeo_err}
+echo "Running spacesavers2_mimeo" 
+command -V ktImportText 2>/dev/null || module load kronatools || (>&2 echo "module kronatools could not be loaded"; exit 1)
+spacesavers2_mimeo \
+    --catalog ${outfile_catalog} \
+    --outdir ${OUTFOLDER} \
+    --quota $QUOTA \
+    --duplicatesonly \
+    --maxdepth 3 \
+    --p $prefix \
+    --kronaplot \
+    > ${outfile_mimeo_log} 2> ${outfile_mimeo_err}
 fi
+
+# spacesavers2_grubbers
 if [ "$?" == "0" ];then
 echo "Running spacesavers2_grubbers" && \
-for f in `ls ${OUTFOLDER}/${prefix}*files.gz`;do
-    outfile=`echo $f|sed "s/files.gz/grubbers.tsv/g"`
-    errfile=`echo $f|sed "s/files.gz/grubbers.err/g"`
-    spacesavers2_grubbers -f $f > $outfile 2> $errfile
+for filegz in `ls ${OUTFOLDER}/${prefix}*files.gz`;do
+    outfile=`echo $filegz|sed "s/mimeo.files.gz/grubbers.tsv/g"`
+    logfile=`echo $filegz|sed "s/mimeo.files.gz/grubbers.log/g"`
+    errfile=`echo $filegz|sed "s/mimeo.files.gz/grubbers.err/g"`
+    spacesavers2_grubbers \
+        --filesgz $filegz \
+        --limit $LIMIT \
+        --outfile $outfile \
+        > $logfile 2> $errfile
 done
 fi
+
+# spacesavers2_blamematrix
 if [ "$?" == "0" ];then
 echo "Running spacesavers2_blamematrix" && \
-spacesavers2_blamematrix -f ${OUTFOLDER}/${prefix}.allusers.files.gz > ${OUTFOLDER}/${prefix}.blamematrix.tsv 2> ${OUTFOLDER}/${prefix}.blamematrix.err
+spacesavers2_blamematrix \
+    --filesgz ${OUTFOLDER}/${prefix}.allusers.mimeo.files.gz \
+    --level $LEVEL \
+    --outfile ${outfile_blamematrix} \
+    > ${outfile_blamematrix_log} 2> ${outfile_blamematrix_err}
 fi
 echo "Done!"
